import { Appointment, Doctor, Notice } from "./types";

export const doctors: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Maya Patel",
    specialty: "Cardiology",
    credentials: "MD, FACC",
    experience: 12,
    rating: 4.9,
    reviews: 128,
    fee: 850,
    color: "#DCEFE9",
    initials: "MP",
    about:
      "Specialist in preventive cardiology, hypertension, and long-term heart health.",
    languages: ["English", "Hindi", "Gujarati"],
    nextAvailable: "Today, 4:30 PM",
    active: true,
  },
  {
    id: "d2",
    name: "Dr. Arjun Mehta",
    specialty: "Dermatology",
    credentials: "MD, DVD",
    experience: 9,
    rating: 4.8,
    reviews: 96,
    fee: 700,
    color: "#F3E9D7",
    initials: "AM",
    about:
      "Evidence-based care for clinical dermatology, allergies, and skin wellness.",
    languages: ["English", "Hindi"],
    nextAvailable: "Tomorrow, 10:00 AM",
    active: true,
  },
  {
    id: "d3",
    name: "Dr. Sarah Wilson",
    specialty: "General Medicine",
    credentials: "MBBS, MRCP",
    experience: 15,
    rating: 4.9,
    reviews: 204,
    fee: 600,
    color: "#E7E4F5",
    initials: "SW",
    about:
      "Comprehensive primary care with a focus on prevention and family health.",
    languages: ["English", "Tamil"],
    nextAvailable: "Today, 6:00 PM",
    active: true,
  },
  {
    id: "d4",
    name: "Dr. Neha Kapoor",
    specialty: "Neurology",
    credentials: "DM, MD",
    experience: 11,
    rating: 4.7,
    reviews: 82,
    fee: 1000,
    color: "#DDEAF4",
    initials: "NK",
    about:
      "Patient-first neurological care for headaches, movement and sleep conditions.",
    languages: ["English", "Hindi", "Punjabi"],
    nextAvailable: "Fri, 11:30 AM",
    active: true,
    onLeave: true,
  },
  {
    id: "d5",
    name: "Dr. Vikram Rao",
    specialty: "Orthopedics",
    credentials: "MS, DNB",
    experience: 14,
    rating: 4.8,
    reviews: 157,
    fee: 800,
    color: "#F4E2E2",
    initials: "VR",
    about:
      "Sports medicine, joint care and rehabilitation plans for active lives.",
    languages: ["English", "Hindi", "Telugu"],
    nextAvailable: "Thu, 3:00 PM",
    active: true,
  },
  {
    id: "d6",
    name: "Dr. Ira Bose",
    specialty: "Pediatrics",
    credentials: "MD, DCH",
    experience: 8,
    rating: 4.9,
    reviews: 111,
    fee: 650,
    color: "#E8EFDA",
    initials: "IB",
    about:
      "Warm, development-focused healthcare for infants, children and teens.",
    languages: ["English", "Hindi", "Bengali"],
    nextAvailable: "Tomorrow, 1:30 PM",
    active: true,
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: "APT-2048",
    doctorId: "d1",
    patientName: "Aarav Sharma",
    date: "2026-08-21",
    time: "10:30 AM",
    type: "In-person visit",
    status: "upcoming",
    symptoms:
      "Occasional chest tightness after climbing stairs with mild shortness of breath for 3 days.",
    urgency: "Medium",
    complaint: "Exertional chest tightness and breathlessness",
    questions: [
      "When did the tightness first begin?",
      "Does the discomfort spread to your arm or jaw?",
      "Any family history of heart disease?",
    ],
    calendarSynced: true,
    emailSent: true,
  },
  {
    id: "APT-2023",
    doctorId: "d3",
    patientName: "Aarav Sharma",
    date: "2026-08-15",
    time: "09:00 AM",
    type: "In-person visit",
    status: "completed",
    symptoms: "Fever, fatigue and sore throat.",
    urgency: "Low",
    complaint: "Viral upper respiratory symptoms",
    questions: [],
    notes: "Likely viral infection. Hydration and rest advised.",
    diagnosis: "Viral pharyngitis",
    summary:
      "You have a common viral throat infection. Rest well, drink plenty of fluids, and take the prescribed medicine after meals. Contact us if fever continues beyond three days.",
    prescription: [
      {
        medicine: "Paracetamol 500mg",
        dose: "1 tablet",
        frequency: "Twice daily, after food",
        duration: "3 days",
      },
    ],
    calendarSynced: true,
    emailSent: true,
  },
  {
    id: "APT-2051",
    doctorId: "d1",
    patientName: "Priya Nair",
    date: "2026-08-20",
    time: "11:15 AM",
    type: "In-person visit",
    status: "upcoming",
    symptoms: "Palpitations occurring at night for the last week.",
    urgency: "Medium",
    complaint: "Nocturnal palpitations",
    questions: [
      "How long does each episode last?",
      "Do you feel dizzy during an episode?",
      "Any recent medication changes?",
    ],
    calendarSynced: true,
    emailSent: true,
  },
  {
    id: "APT-2052",
    doctorId: "d1",
    patientName: "Rohan Das",
    date: "2026-08-20",
    time: "12:00 PM",
    type: "In-person visit",
    status: "upcoming",
    symptoms: "Sudden severe chest pain and sweating this morning.",
    urgency: "High",
    complaint: "Acute chest pain with diaphoresis",
    questions: [
      "Is the pain still present?",
      "Does it spread to your back, jaw, or arm?",
      "Have you contacted emergency services?",
    ],
    calendarSynced: false,
    emailSent: true,
  },
];

export const initialNotices: Notice[] = [
  {
    id: "n1",
    title: "Appointment confirmed",
    detail: "Your visit with Dr. Maya Patel is scheduled.",
    time: "12 min ago",
    read: false,
    type: "success",
  },
  {
    id: "n2",
    title: "Medication reminder",
    detail: "Paracetamol 500mg · 1 tablet after food",
    time: "1 hr ago",
    read: false,
    type: "info",
  },
  {
    id: "n3",
    title: "Calendar connected",
    detail: "Google Calendar is up to date.",
    time: "Yesterday",
    read: true,
    type: "success",
  },
];
